import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientApplication from "./(Components)/ClientApplication";
import { Providers } from "./(Components)/GlobalRedux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Book Rental",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
        <ClientApplication>
        {children}
        </ClientApplication>
        </Providers>
        </body>
    </html>
  );
}
